pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'kuzan2077/ngadena-flask-app'
        GITHUB_URL = 'https://github.com/Hera-2077/tpdocker.git'
        DOCKERHUB_CREDS = 'dockerhub-id' 
    }

    stages {
        stage('Clonage') {
            steps {
                echo 'Clonage du dépôt GitHub...'
                git branch: 'main', url: "${GITHUB_URL}"
            }
        }

        stage('Image') {
            steps {
                echo 'Construction de l\'image Docker...'
                // Construire l'image [cite: 55]
                sh 'docker build -t ${DOCKER_IMAGE}:latest .'
            }
        }

        stage('Publication') {
            steps {
                echo 'Publication sur DockerHub...'
                // Publier votre image sur DockerHub [cite: 56]
                withCredentials([usernamePassword(credentialsId: env.DOCKERHUB_CREDS, passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    sh "docker push ${DOCKER_IMAGE}:latest"
                }
            }
        }
    }
}